package com.cloudedhorizons.client;

import java.io.IOException;
import java.io.InputStream;
import java.nio.ByteBuffer;
import java.nio.FloatBuffer;
import java.nio.IntBuffer;
import java.nio.charset.StandardCharsets;
import java.util.List;

import net.minecraft.client.Minecraft;
import net.minecraft.client.renderer.GLAllocation;
import net.minecraft.client.renderer.entity.RenderManager;
import net.minecraft.util.Vec3;
import net.minecraft.world.World;

import org.lwjgl.opengl.GL;
import org.lwjgl.opengl.GL11;
import org.lwjgl.opengl.GL12;
import org.lwjgl.opengl.GL13;
import org.lwjgl.opengl.GL14;
import org.lwjgl.opengl.GL15;
import org.lwjgl.opengl.GL20;
import org.lwjgl.opengl.GL30;
import org.lwjgl.opengl.GL33;
import org.lwjgl.opengl.GL40;
import org.lwjgl.opengl.GL42;
import org.lwjgl.opengl.GL43;

import org.apache.commons.io.IOUtils;

import com.cloudedhorizons.CloudedHorizons;
import com.cloudedhorizons.Config;
import com.cloudedhorizons.NoiseLayer;

/**
 * GPU cloud renderer (needs OpenGL 4.3).
 * <ol>
 * <li>Generation: a fragment shader writes the voxel field into a 3D texture, one layer per draw. Regeneration is
 * spread over frames, one slab of {@link #SLAB_LAYERS} layers per frame, and a new pass starts every
 * {@link #REGEN_INTERVAL_TICKS} ticks at most while the clouds morph (the field's time axis advances at
 * {@link #getMorphSpeed()}).</li>
 * <li>Meshing: after each complete pass, compute shaders turn the voxels into faces (one quad per solid voxel side
 * next to empty space), grouped per chunk of {@link #CHUNK_SIZE} x {@link #CHUNK_SIZE} voxel columns. Each chunk
 * has its own range of the face buffer and its own indirect draw command, so chunks can later get their own LOD or
 * be culled.</li>
 * <li>Drawing: opaque depth pass, weighted blended translucent pass, then a fullscreen resolve.
 * Both mesh passes use the same continuous ambient lighting.</li>
 * </ol>
 */
public final class CloudRenderer {

    private static final int VOXEL_SIZE = 8;
    /** Requested horizontal size of the field in voxels (X and Z); limited by the GPU's 3D texture size. */
    private static final int FIELD_SIZE = 2560;
    /** Upper limit for the number of voxel layers, to keep the 3D texture and regeneration cost bounded. */
    private static final int MAX_LAYERS = 128;
    /** Voxel layers regenerated per frame. */
    private static final int SLAB_LAYERS = 4;
    /** Chunk size in voxels along X and Z; must be a multiple of 8 (the mesher's workgroup size). */
    private static final int CHUNK_SIZE = 32;
    /** Face buffer capacity (8 bytes per face). Faces beyond it are not drawn. */
    private static final int MAX_FACES = 1 << 26;
    /** Bytes per chunk record in the chunk buffer and per indirect draw command (4 uints each). */
    private static final int CHUNK_BYTES = 16;

    /** Actual horizontal size in voxels, set at initialisation. */
    private static int sizeX;
    private static int sizeZ;
    /** World position of the volume's minimum corner, centred on the world origin. */
    private static double originX;
    private static double originZ;
    private static final int SEED = 1;
    /** Regenerate the volume at most this often, in world ticks. */
    private static final double REGEN_INTERVAL_TICKS = 2.0D;

    private static double morphPhase;
    private static double lastWorldTime = Double.NaN;
    private static double lastRegenTime = Double.NEGATIVE_INFINITY;

    /** Minimum time between config writes, so sliders do not rewrite the file every frame. */
    private static final long SAVE_INTERVAL_MS = 1000L;
    private static boolean configDirty;
    private static long lastSaveMs;
    /** Faces the last meshing produced, including those past MAX_FACES that were dropped. */
    private static long lastFaceCount;
    private static long lastOverflowWarnMs;
    private static boolean overflowing;
    private static final IntBuffer FACE_COUNT = GLAllocation.createDirectIntBuffer(1);

    /** Set when a field parameter changes; a regeneration pass is started or queued on the next frame. */
    private static boolean fieldDirty;
    /** Slab being regenerated by the current pass, or -1 when no pass is running. */
    private static int regenSlab = -1;
    /** Another pass is needed after the current one, because the field changed while it ran. */
    private static boolean regenQueued;
    /** Number of voxel layers the 3D texture is currently allocated with. */
    private static int allocatedLayers;
    /** The voxel texture changed since the last meshing. */
    private static boolean meshDirty;
    /** Chunk grid size, set at initialisation. */
    private static int chunksX;
    private static int chunksZ;

    private static boolean initialized;
    private static boolean failed;

    private static int voxelTexture;
    private static int generateProgram;
    private static int meshCountProgram;
    private static int meshScanProgram;
    private static int meshEmitProgram;
    private static int drawProgram;
    private static int compositeProgram;
    private static int translucentProgram;
    private static int cloudFbo;
    private static int cloudAccumulation;
    private static int cloudSceneDepth;
    private static int cloudWidth;
    private static int cloudHeight;
    private static int emptyVao;
    private static int generateFbo;
    /** Faces (uvec2 each), per-chunk records and per-chunk indirect draw commands; see mesh.comp. */
    private static int faceBuffer;
    private static int chunkBuffer;
    private static int drawBuffer;

    private static final FloatBuffer MATRIX = GLAllocation.createDirectFloatBuffer(16);
    private static final FloatBuffer PROJECTION = GLAllocation.createDirectFloatBuffer(16);
    private static final DrawState DRAW_STATE = new DrawState();
    private static final IntBuffer GENERATE_VIEWPORT = GLAllocation.createDirectIntBuffer(4);

    private CloudRenderer() {}

    public static double getMorphSpeed() {
        return Config.morphSpeed;
    }

    public static void setMorphSpeed(double speed) {
        Config.morphSpeed = speed;
        saveLater();
    }

    public static double getBaseY() {
        return Config.cloudHeight;
    }

    public static void setBaseY(double y) {
        // Only affects placement, so changing it needs no regeneration.
        Config.cloudHeight = y;
        saveLater();
    }

    /** Height of the cloud field in voxels. */
    public static int getFieldHeight() {
        return Config.fieldHeight;
    }

    public static void setFieldHeight(int voxels) {
        // The texture is reallocated and regenerated on the next frame (see render).
        Config.fieldHeight = voxels;
        saveLater();
    }

    public static double getCutoff() {
        return Config.cutoff;
    }

    public static void setCutoff(double cutoff) {
        Config.cutoff = cutoff;
        fieldChanged();
    }

    public static double getSoftness() {
        return Config.softness;
    }

    public static void setSoftness(double softness) {
        Config.softness = softness;
        fieldChanged();
    }

    public static double getEdgeFade() {
        return Config.edgeFade;
    }

    public static void setEdgeFade(double voxels) {
        Config.edgeFade = voxels;
        fieldChanged();
    }

    /** The noise layers, summed before the cutoff test. Edit a layer's fields, then call {@link #fieldChanged()}. */
    public static List<NoiseLayer> getNoiseLayers() {
        return Config.noiseLayers;
    }

    /**
     * Adds a layer after the last one, one octave finer: half its scale and half its multiplier. Returns the new
     * layer's index, or -1 if the maximum is reached.
     */
    public static int addNoiseLayer() {
        List<NoiseLayer> layers = Config.noiseLayers;
        if (layers.size() >= Config.MAX_NOISE_LAYERS) {
            return -1;
        }
        NoiseLayer layer = layers.get(layers.size() - 1).copy();
        layer.scaleX = Math.max(1.0D, layer.scaleX / 2.0D);
        layer.scaleY = Math.max(1.0D, layer.scaleY / 2.0D);
        layer.scaleZ = Math.max(1.0D, layer.scaleZ / 2.0D);
        layer.multiplier /= 2.0D;
        layer.offset = 0.0D;
        layers.add(layer);
        fieldChanged();
        return layers.size() - 1;
    }

    /** Removes a layer; the last remaining layer cannot be removed. */
    public static void removeNoiseLayer(int index) {
        List<NoiseLayer> layers = Config.noiseLayers;
        if (layers.size() > 1 && index >= 0 && index < layers.size()) {
            layers.remove(index);
            fieldChanged();
        }
    }

    /** Marks the cloud settings for saving; {@link #saveIfDue()} writes them from the render loop. */
    private static void saveLater() {
        configDirty = true;
    }

    private static void saveIfDue() {
        long now = System.currentTimeMillis();
        if (configDirty && now - lastSaveMs >= SAVE_INTERVAL_MS) {
            configDirty = false;
            lastSaveMs = now;
            Config.saveClouds();
        }
    }

    /** Call after changing a field parameter: regenerates the clouds and saves the config. */
    public static void fieldChanged() {
        fieldDirty = true;
        saveLater();
    }

    /**
     * Far plane distance in blocks needed to see the whole cloud field from anywhere inside it (the field's diagonal).
     * Used by MixinEntityRenderer. Before initialisation, the requested field size is assumed.
     */
    public static float getFarPlane() {
        int size = initialized ? Math.max(sizeX, sizeZ) : FIELD_SIZE;
        return (float) (size * VOXEL_SIZE * Math.sqrt(2.0D));
    }

    /** Voxel layers to allocate: the configured field height, limited to 1..MAX_LAYERS. */
    private static int layers() {
        return Math.max(1, Math.min(MAX_LAYERS, Config.fieldHeight));
    }

    public static void render(Minecraft mc, World world, float partialTicks) {
        if (failed) {
            return;
        }
        if (!GL.getCapabilities().OpenGL43) {
            failed = true;
            CloudedHorizons.LOG.error("OpenGL 4.3 is required for GPU clouds");
            return;
        }
        // Generation, allocation and meshing also change state. Protect the complete render operation.
        DRAW_STATE.capture();
        try {
            GL13.glActiveTexture(GL13.GL_TEXTURE0);
            renderClouds(mc, world, partialTicks);
        } finally {
            DRAW_STATE.restore();
            // Keep the old cloud hook's white fixed-function modulation for the hand and GUI.
            GL11.glColor4f(1.0F, 1.0F, 1.0F, 1.0F);
        }
    }

    private static void renderClouds(Minecraft mc, World world, float partialTicks) {
        if (failed) {
            return;
        }
        if (!initialized) {
            try {
                initialize(mc);
            } catch (RuntimeException e) {
                failed = true;
                CloudedHorizons.LOG.error("GPU cloud initialisation failed, clouds disabled", e);
                return;
            }
        }
        if (layers() != allocatedLayers) {
            // New storage has undefined contents, so fill it completely before drawing.
            allocateTextures();
            generateAll(mc);
        }
        updateMorph(world, partialTicks);
        if (fieldDirty) {
            fieldDirty = false;
            startRegen();
        }
        if (regenSlab >= 0) {
            generateLayers(mc, regenSlab * SLAB_LAYERS, SLAB_LAYERS);
            regenSlab++;
            if (regenSlab >= slabs()) {
                regenSlab = regenQueued ? 0 : -1;
                regenQueued = false;
                meshDirty = true;
            }
        }
        if (meshDirty) {
            meshDirty = false;
            buildMesh();
        }
        saveIfDue();
        draw(world, partialTicks);
    }

    private static void draw(World world, float partialTicks) {
        GL11.glGetFloatv(GL11.GL_MODELVIEW_MATRIX, MATRIX);
        GL11.glGetFloatv(GL11.GL_PROJECTION_MATRIX, PROJECTION);

        Vec3 colour = world.getCloudColour(partialTicks);

        drawClouds(colour, DRAW_STATE);
    }

    private static void drawClouds(Vec3 colour, DrawState state) {
        GL11.glEnable(GL11.GL_DEPTH_TEST);
        GL11.glDepthFunc(GL11.GL_LEQUAL);
        GL11.glDepthMask(true);
        GL11.glDisable(GL11.GL_BLEND);
        GL11.glDisable(GL11.GL_ALPHA_TEST);
        GL11.glEnable(GL11.GL_CULL_FACE);
        GL11.glCullFace(GL11.GL_BACK);

        setDrawUniforms(drawProgram, colour);
        GL30.glBindBufferBase(GL43.GL_SHADER_STORAGE_BUFFER, 0, faceBuffer);
        GL15.glBindBuffer(GL40.GL_DRAW_INDIRECT_BUFFER, drawBuffer);
        GL30.glBindVertexArray(emptyVao);
        int passLocation = GL20.glGetUniformLocation(drawProgram, "uTranslucentPass");
        GL20.glUniform1i(passLocation, 0);
        GL43.glMultiDrawArraysIndirect(GL11.GL_TRIANGLES, 0L, chunksX * chunksZ, 0);

        // Capture world + opaque-cloud depth from the current destination, not an assumed vanilla framebuffer.
        // Copying depth into a texture allows format conversion without depth-blit format restrictions.
        ensureCloudTargets(state.viewport.get(2), state.viewport.get(3));
        GL30.glBindFramebuffer(GL30.GL_READ_FRAMEBUFFER, state.drawFbo);
        GL13.glActiveTexture(GL13.GL_TEXTURE0);
        GL11.glBindTexture(GL11.GL_TEXTURE_2D, cloudSceneDepth);
        GL33.glBindSampler(0, 0);
        GL11.glCopyTexSubImage2D(
                GL11.GL_TEXTURE_2D, 0, 0, 0, state.viewport.get(0), state.viewport.get(1), cloudWidth, cloudHeight);
        GL30.glBindFramebuffer(GL30.GL_DRAW_FRAMEBUFFER, cloudFbo);
        GL11.glViewport(0, 0, cloudWidth, cloudHeight);
        GL11.glDisable(GL11.GL_SCISSOR_TEST);
        GL11.glDisable(GL11.GL_STENCIL_TEST);
        GL11.glDisable(GL11.GL_DEPTH_TEST);
        GL11.glDepthMask(false);
        GL11.glColorMask(true, true, true, true);
        FloatBuffer clear = state.clear;
        clear.put(0, 0.0F).put(1, 0.0F).put(2, 0.0F).put(3, 0.0F);
        GL30.glClearBufferfv(GL11.GL_COLOR, 0, clear);
        // All channels use additive blending. Avoid indexed blend/mask calls: they can bypass
        // Angelica's tracking of the global state used by subsequent world, hand and GUI draws.
        GL11.glEnable(GL11.GL_BLEND);
        GL20.glBlendEquationSeparate(GL14.GL_FUNC_ADD, GL14.GL_FUNC_ADD);
        GL14.glBlendFuncSeparate(GL11.GL_ONE, GL11.GL_ONE, GL11.GL_ONE, GL11.GL_ONE);
        setDrawUniforms(translucentProgram, colour);
        GL20.glUniform1i(GL20.glGetUniformLocation(translucentProgram, "uTranslucentPass"), 1);
        GL43.glMultiDrawArraysIndirect(GL11.GL_TRIANGLES, 0L, chunksX * chunksZ, 0);

        // Resolve the weighted colour and combined opacity once over the opaque destination.
        GL30.glBindFramebuffer(GL30.GL_DRAW_FRAMEBUFFER, state.drawFbo);
        state.restoreViewportAndMask();
        setEnabled(GL11.GL_SCISSOR_TEST, state.scissor);
        setEnabled(GL11.GL_STENCIL_TEST, state.stencil);
        GL11.glDisable(GL11.GL_CULL_FACE);
        GL20.glBlendEquationSeparate(GL14.GL_FUNC_ADD, GL14.GL_FUNC_ADD);
        GL14.glBlendFuncSeparate(
                GL11.GL_SRC_ALPHA, GL11.GL_ONE_MINUS_SRC_ALPHA, GL11.GL_ONE, GL11.GL_ONE_MINUS_SRC_ALPHA);
        GL20.glUseProgram(compositeProgram);
        GL20.glUniform1i(GL20.glGetUniformLocation(compositeProgram, "uAccumulation"), 0);
        GL20.glUniform3f(
                GL20.glGetUniformLocation(compositeProgram, "uColour"),
                (float) colour.xCoord,
                (float) colour.yCoord,
                (float) colour.zCoord);
        GL20.glUniform2i(
                GL20.glGetUniformLocation(compositeProgram, "uViewportOrigin"),
                state.viewport.get(0),
                state.viewport.get(1));
        GL13.glActiveTexture(GL13.GL_TEXTURE0);
        GL11.glBindTexture(GL11.GL_TEXTURE_2D, cloudAccumulation);
        GL11.glDrawArrays(GL11.GL_TRIANGLES, 0, 3);
    }

    private static void setDrawUniforms(int program, Vec3 colour) {
        GL20.glUseProgram(program);
        GL20.glUniformMatrix4fv(GL20.glGetUniformLocation(program, "uProj"), false, PROJECTION);
        GL20.glUniformMatrix4fv(GL20.glGetUniformLocation(program, "uView"), false, MATRIX);
        GL20.glUniform3f(
                GL20.glGetUniformLocation(program, "uBoxMin"),
                (float) (originX - RenderManager.renderPosX),
                (float) (Config.cloudHeight - RenderManager.renderPosY),
                (float) (originZ - RenderManager.renderPosZ));
        GL20.glUniform1f(GL20.glGetUniformLocation(program, "uVS"), VOXEL_SIZE);
        GL20.glUniform1f(GL20.glGetUniformLocation(program, "uFieldHeight"), allocatedLayers);
        GL20.glUniform3f(
                GL20.glGetUniformLocation(program, "uColour"),
                (float) colour.xCoord,
                (float) colour.yCoord,
                (float) colour.zCoord);
        GL20.glUniform1i(GL20.glGetUniformLocation(program, "uSceneDepth"), 0);
    }

    /** Screen-sized targets are reused, with storage replaced only when the viewport changes size. */
    private static void ensureCloudTargets(int width, int height) {
        if (cloudWidth == width && cloudHeight == height) {
            return;
        }
        if (cloudFbo == 0) {
            cloudFbo = GL30.glGenFramebuffers();
            cloudAccumulation = GL11.glGenTextures();
            cloudSceneDepth = GL11.glGenTextures();
        }
        GL13.glActiveTexture(GL13.GL_TEXTURE0);
        // Thousands of overlapping voxels can lose significant colour precision in a half-float sum.
        allocateCloudTarget(cloudAccumulation, GL30.GL_RGBA32F, GL11.GL_RGBA, width, height);
        allocateCloudTarget(cloudSceneDepth, GL30.GL_DEPTH_COMPONENT32F, GL11.GL_DEPTH_COMPONENT, width, height);
        GL30.glBindFramebuffer(GL30.GL_DRAW_FRAMEBUFFER, cloudFbo);
        GL30.glFramebufferTexture2D(
                GL30.GL_DRAW_FRAMEBUFFER, GL30.GL_COLOR_ATTACHMENT0, GL11.GL_TEXTURE_2D, cloudAccumulation, 0);
        GL11.glDrawBuffer(GL30.GL_COLOR_ATTACHMENT0);
        checkFramebuffer("Cloud transparency");
        cloudWidth = width;
        cloudHeight = height;
    }

    private static void allocateCloudTarget(int texture, int internalFormat, int format, int width, int height) {
        GL11.glBindTexture(GL11.GL_TEXTURE_2D, texture);
        GL11.glTexParameteri(GL11.GL_TEXTURE_2D, GL11.GL_TEXTURE_MIN_FILTER, GL11.GL_NEAREST);
        GL11.glTexParameteri(GL11.GL_TEXTURE_2D, GL11.GL_TEXTURE_MAG_FILTER, GL11.GL_NEAREST);
        GL11.glTexParameteri(GL11.GL_TEXTURE_2D, GL11.GL_TEXTURE_WRAP_S, GL12.GL_CLAMP_TO_EDGE);
        GL11.glTexParameteri(GL11.GL_TEXTURE_2D, GL11.GL_TEXTURE_WRAP_T, GL12.GL_CLAMP_TO_EDGE);
        GL11.glTexImage2D(GL11.GL_TEXTURE_2D, 0, internalFormat, width, height, 0, format, GL11.GL_FLOAT, (ByteBuffer) null);
    }

    private static void setEnabled(int capability, boolean enabled) {
        if (enabled) {
            GL11.glEnable(capability);
        } else {
            GL11.glDisable(capability);
        }
    }

    /** Use the same global GL entry points as Minecraft so Angelica's state cache stays consistent. */
    private static final class DrawState {
        int drawFbo;
        int readFbo;
        int program;
        int vao;
        int indirectBuffer;
        int storageBuffer;
        int activeTexture;
        int texture2D;
        int texture3D;
        int sampler;
        int depthFunc;
        int cullMode;
        boolean depth;
        boolean depthMask;
        boolean cull;
        boolean alpha;
        boolean scissor;
        boolean stencil;
        boolean blend;
        final IntBuffer viewport = GLAllocation.createDirectIntBuffer(4);
        final FloatBuffer clear = GLAllocation.createDirectFloatBuffer(4);
        final ByteBuffer mask = GLAllocation.createDirectByteBuffer(4);
        final int[] storageBindings = new int[3];
        final int[] blendValues = new int[6];
        final int[] blendKeys = {
                GL14.GL_BLEND_SRC_RGB,
                GL14.GL_BLEND_DST_RGB,
                GL14.GL_BLEND_SRC_ALPHA,
                GL14.GL_BLEND_DST_ALPHA,
                GL20.GL_BLEND_EQUATION_RGB,
                GL20.GL_BLEND_EQUATION_ALPHA };

        void capture() {
            drawFbo = GL11.glGetInteger(GL30.GL_DRAW_FRAMEBUFFER_BINDING);
            readFbo = GL11.glGetInteger(GL30.GL_READ_FRAMEBUFFER_BINDING);
            program = GL11.glGetInteger(GL20.GL_CURRENT_PROGRAM);
            vao = GL11.glGetInteger(GL30.GL_VERTEX_ARRAY_BINDING);
            indirectBuffer = GL11.glGetInteger(GL40.GL_DRAW_INDIRECT_BUFFER_BINDING);
            storageBuffer = GL11.glGetInteger(GL43.GL_SHADER_STORAGE_BUFFER_BINDING);
            for (int i = 0; i < storageBindings.length; i++) {
                storageBindings[i] = GL30.glGetIntegeri(GL43.GL_SHADER_STORAGE_BUFFER_BINDING, i);
            }
            activeTexture = GL11.glGetInteger(GL13.GL_ACTIVE_TEXTURE);
            GL13.glActiveTexture(GL13.GL_TEXTURE0);
            texture2D = GL11.glGetInteger(GL11.GL_TEXTURE_BINDING_2D);
            texture3D = GL11.glGetInteger(GL12.GL_TEXTURE_BINDING_3D);
            sampler = GL30.glGetIntegeri(GL33.GL_SAMPLER_BINDING, 0);
            GL13.glActiveTexture(activeTexture);
            depthFunc = GL11.glGetInteger(GL11.GL_DEPTH_FUNC);
            cullMode = GL11.glGetInteger(GL11.GL_CULL_FACE_MODE);
            depth = GL11.glIsEnabled(GL11.GL_DEPTH_TEST);
            depthMask = GL11.glGetBoolean(GL11.GL_DEPTH_WRITEMASK);
            cull = GL11.glIsEnabled(GL11.GL_CULL_FACE);
            alpha = GL11.glIsEnabled(GL11.GL_ALPHA_TEST);
            scissor = GL11.glIsEnabled(GL11.GL_SCISSOR_TEST);
            stencil = GL11.glIsEnabled(GL11.GL_STENCIL_TEST);
            blend = GL11.glIsEnabled(GL11.GL_BLEND);
            GL11.glGetIntegerv(GL11.GL_VIEWPORT, viewport);
            GL11.glGetBooleanv(GL11.GL_COLOR_WRITEMASK, mask);
            for (int i = 0; i < blendKeys.length; i++) {
                blendValues[i] = GL11.glGetInteger(blendKeys[i]);
            }
        }

        void restoreViewportAndMask() {
            GL11.glViewport(viewport.get(0), viewport.get(1), viewport.get(2), viewport.get(3));
            GL11.glColorMask(mask.get(0) != 0, mask.get(1) != 0, mask.get(2) != 0, mask.get(3) != 0);
        }

        void restore() {
            GL30.glBindFramebuffer(GL30.GL_DRAW_FRAMEBUFFER, drawFbo);
            GL30.glBindFramebuffer(GL30.GL_READ_FRAMEBUFFER, readFbo);
            restoreViewportAndMask();
            GL13.glActiveTexture(GL13.GL_TEXTURE0);
            GL11.glBindTexture(GL11.GL_TEXTURE_2D, texture2D);
            GL11.glBindTexture(GL12.GL_TEXTURE_3D, texture3D);
            GL33.glBindSampler(0, sampler);
            GL13.glActiveTexture(activeTexture);
            GL14.glBlendFuncSeparate(blendValues[0], blendValues[1], blendValues[2], blendValues[3]);
            GL20.glBlendEquationSeparate(blendValues[4], blendValues[5]);
            setEnabled(GL11.GL_BLEND, blend);
            GL11.glDepthMask(depthMask);
            GL11.glDepthFunc(depthFunc);
            GL11.glCullFace(cullMode);
            setEnabled(GL11.GL_DEPTH_TEST, depth);
            setEnabled(GL11.GL_CULL_FACE, cull);
            setEnabled(GL11.GL_ALPHA_TEST, alpha);
            setEnabled(GL11.GL_SCISSOR_TEST, scissor);
            setEnabled(GL11.GL_STENCIL_TEST, stencil);
            GL20.glUseProgram(program);
            GL30.glBindVertexArray(vao);
            GL15.glBindBuffer(GL40.GL_DRAW_INDIRECT_BUFFER, indirectBuffer);
            for (int i = 0; i < storageBindings.length; i++) {
                GL30.glBindBufferBase(GL43.GL_SHADER_STORAGE_BUFFER, i, storageBindings[i]);
            }
            GL15.glBindBuffer(GL43.GL_SHADER_STORAGE_BUFFER, storageBuffer);
        }
    }

    private static void initialize(Minecraft mc) {
        initialized = true;
        if (!GL.getCapabilities().OpenGL43) {
            throw new IllegalStateException("OpenGL 4.3 is required (compute shaders, storage buffers, indirect draws)");
        }
        int max3d = GL11.glGetInteger(GL12.GL_MAX_3D_TEXTURE_SIZE);
        // Also keep the size a whole number of chunks, so every mesher workgroup lies in one chunk.
        sizeX = Math.min(FIELD_SIZE, max3d) / CHUNK_SIZE * CHUNK_SIZE;
        sizeZ = sizeX;
        if (sizeX < FIELD_SIZE) {
            CloudedHorizons.LOG.warn(
                    "GL_MAX_3D_TEXTURE_SIZE is {}; cloud field limited to {} voxels instead of {}",
                    max3d,
                    sizeX,
                    FIELD_SIZE);
        }
        originX = -sizeX * VOXEL_SIZE / 2.0D;
        originZ = -sizeZ * VOXEL_SIZE / 2.0D;
        chunksX = sizeX / CHUNK_SIZE;
        chunksZ = sizeZ / CHUNK_SIZE;

        generateProgram = createProgram("fullscreen.vsh", "generate.fsh", "noise.fsh");
        meshCountProgram = createComputeProgram("mesh.comp", null);
        meshEmitProgram = createComputeProgram("mesh.comp", "EMIT");
        meshScanProgram = createComputeProgram("mesh_scan.comp", null);
        drawProgram = createProgram("mesh.vsh", "mesh.fsh");
        translucentProgram = createDefinedProgram("TRANSLUCENT", "mesh.vsh", "mesh.fsh");
        compositeProgram = createProgram("fullscreen.vsh", "cloud_composite.fsh");
        emptyVao = GL30.glGenVertexArrays();
        voxelTexture = createTexture3D();
        allocateTextures();
        generateFbo = GL30.glGenFramebuffers();
        createMeshBuffers();
        generateAll(mc);
    }

    private static void createMeshBuffers() {
        int chunks = chunksX * chunksZ;
        faceBuffer = createBuffer(GL43.GL_SHADER_STORAGE_BUFFER, (long) MAX_FACES * 8L);
        // The mesher expects zeroed chunk counters; the scan pass resets them after each use.
        chunkBuffer = GL15.glGenBuffers();
        GL15.glBindBuffer(GL43.GL_SHADER_STORAGE_BUFFER, chunkBuffer);
        GL15.glBufferData(
                GL43.GL_SHADER_STORAGE_BUFFER,
                GLAllocation.createDirectByteBuffer(chunks * CHUNK_BYTES),
                GL15.GL_DYNAMIC_DRAW);
        GL15.glBindBuffer(GL43.GL_SHADER_STORAGE_BUFFER, 0);
        // Zeroed commands draw nothing until the first meshing.
        drawBuffer = GL15.glGenBuffers();
        GL15.glBindBuffer(GL40.GL_DRAW_INDIRECT_BUFFER, drawBuffer);
        GL15.glBufferData(
                GL40.GL_DRAW_INDIRECT_BUFFER,
                GLAllocation.createDirectByteBuffer(chunks * CHUNK_BYTES),
                GL15.GL_DYNAMIC_DRAW);
        GL15.glBindBuffer(GL40.GL_DRAW_INDIRECT_BUFFER, 0);
    }

    private static int createBuffer(int target, long bytes) {
        int buffer = GL15.glGenBuffers();
        GL15.glBindBuffer(target, buffer);
        GL15.glBufferData(target, bytes, GL15.GL_DYNAMIC_DRAW);
        GL15.glBindBuffer(target, 0);
        return buffer;
    }

    /** Starts a regeneration pass, or queues one if a pass is already running. */
    private static void startRegen() {
        if (regenSlab < 0) {
            regenSlab = 0;
        } else {
            regenQueued = true;
        }
    }

    /** Regenerates the whole volume at once, cancels any running pass, and requests a new mesh. */
    private static void generateAll(Minecraft mc) {
        regenSlab = -1;
        regenQueued = false;
        fieldDirty = false;
        generateLayers(mc, 0, allocatedLayers);
        meshDirty = true;
    }

    /** Number of slabs of {@link #SLAB_LAYERS} layers. */
    private static int slabs() {
        return (allocatedLayers + SLAB_LAYERS - 1) / SLAB_LAYERS;
    }

    /**
     * Advances the morph phase by the game time elapsed since the last frame, so it stops while the game is paused
     * and a speed change does not make it jump.
     */
    private static void updateMorph(World world, float partialTicks) {
        double now = world.getTotalWorldTime() + partialTicks;
        if (Double.isNaN(lastWorldTime) || now < lastWorldTime || now - lastWorldTime > 100.0D) {
            // First frame, world change, or a large time skip: do not advance.
            lastWorldTime = now;
            return;
        }
        morphPhase += (now - lastWorldTime) / 20.0D * Config.morphSpeed;
        lastWorldTime = now;
        // Start the next pass once the previous one is done; passes take several frames.
        if (Config.morphSpeed != 0.0D && regenSlab < 0 && now - lastRegenTime >= REGEN_INTERVAL_TICKS) {
            lastRegenTime = now;
            startRegen();
        }
    }

    private static int createTexture3D() {
        int texture = GL11.glGenTextures();
        GL11.glBindTexture(GL12.GL_TEXTURE_3D, texture);
        GL11.glTexParameteri(GL12.GL_TEXTURE_3D, GL11.GL_TEXTURE_MIN_FILTER, GL11.GL_NEAREST);
        GL11.glTexParameteri(GL12.GL_TEXTURE_3D, GL11.GL_TEXTURE_MAG_FILTER, GL11.GL_NEAREST);
        GL11.glTexParameteri(GL12.GL_TEXTURE_3D, GL11.GL_TEXTURE_WRAP_S, GL12.GL_CLAMP_TO_EDGE);
        GL11.glTexParameteri(GL12.GL_TEXTURE_3D, GL11.GL_TEXTURE_WRAP_T, GL12.GL_CLAMP_TO_EDGE);
        GL11.glTexParameteri(GL12.GL_TEXTURE_3D, GL12.GL_TEXTURE_WRAP_R, GL12.GL_CLAMP_TO_EDGE);
        GL11.glTexParameteri(GL12.GL_TEXTURE_3D, GL12.GL_TEXTURE_MAX_LEVEL, 0);
        GL11.glBindTexture(GL12.GL_TEXTURE_3D, 0);
        return texture;
    }

    /** (Re)allocates the voxel texture storage for the configured field height. Layout (x, z, y). */
    private static void allocateTextures() {
        allocatedLayers = layers();
        GL11.glBindTexture(GL12.GL_TEXTURE_3D, voxelTexture);
        GL12.glTexImage3D(
                GL12.GL_TEXTURE_3D,
                0,
                GL30.GL_R8,
                sizeX,
                sizeZ,
                allocatedLayers,
                0,
                GL11.GL_RED,
                GL11.GL_UNSIGNED_BYTE,
                (ByteBuffer) null);
        GL11.glBindTexture(GL12.GL_TEXTURE_3D, 0);
    }

    /**
     * Regenerates {@code count} voxel layers starting at {@code firstLayer} by running the generation shader once
     * per layer, then restores Minecraft's GL state.
     */
    private static void generateLayers(Minecraft mc, int firstLayer, int count) {
        int endLayer = Math.min(allocatedLayers, firstLayer + count);
        int previousDrawFbo = GL11.glGetInteger(GL30.GL_DRAW_FRAMEBUFFER_BINDING);
        int previousReadFbo = GL11.glGetInteger(GL30.GL_READ_FRAMEBUFFER_BINDING);
        GL11.glGetIntegerv(GL11.GL_VIEWPORT, GENERATE_VIEWPORT);

        // Nothing may sample the texture being written.
        GL13.glActiveTexture(GL13.GL_TEXTURE0);
        GL11.glBindTexture(GL12.GL_TEXTURE_3D, 0);
        GL30.glBindFramebuffer(GL30.GL_FRAMEBUFFER, generateFbo);
        GL11.glViewport(0, 0, sizeX, sizeZ);
        GL11.glDisable(GL11.GL_DEPTH_TEST);
        GL11.glDisable(GL11.GL_BLEND);
        GL11.glDisable(GL11.GL_CULL_FACE);

        GL20.glUseProgram(generateProgram);
        GL20.glUniform1f(GL20.glGetUniformLocation(generateProgram, "uVS"), VOXEL_SIZE);
        GL20.glUniform2f(
                GL20.glGetUniformLocation(generateProgram, "uOriginXZ"),
                (float) originX,
                (float) originZ);
        GL30.glUniform1ui(GL20.glGetUniformLocation(generateProgram, "uSeed"), SEED);
        List<NoiseLayer> layers = Config.noiseLayers;
        GL20.glUniform1i(GL20.glGetUniformLocation(generateProgram, "uNoiseLayers"), layers.size());
        for (int i = 0; i < layers.size(); i++) {
            NoiseLayer layer = layers.get(i);
            GL20.glUniform3f(
                    GL20.glGetUniformLocation(generateProgram, "uLayerScale[" + i + "]"),
                    (float) layer.scaleX,
                    (float) layer.scaleY,
                    (float) layer.scaleZ);
            GL20.glUniform2f(
                    GL20.glGetUniformLocation(generateProgram, "uLayerMulOffset[" + i + "]"),
                    (float) layer.multiplier,
                    (float) layer.offset);
        }
        GL20.glUniform1f(GL20.glGetUniformLocation(generateProgram, "uCutoff"), (float) Config.cutoff);
        GL20.glUniform1f(GL20.glGetUniformLocation(generateProgram, "uEdgeFade"), (float) Config.edgeFade);
        GL20.glUniform1f(GL20.glGetUniformLocation(generateProgram, "uSoftness"), (float) Config.softness);
        GL20.glUniform1i(GL20.glGetUniformLocation(generateProgram, "uLayers"), allocatedLayers);
        // Wrapped so float precision in the shader stays good over long sessions; the jump is rare and slow.
        GL20.glUniform1f(GL20.glGetUniformLocation(generateProgram, "uEvolve"), (float) (morphPhase % 1000.0D));
        int layerLocation = GL20.glGetUniformLocation(generateProgram, "uLayer");

        GL30.glBindVertexArray(emptyVao);
        for (int layer = firstLayer; layer < endLayer; layer++) {
            GL30.glFramebufferTextureLayer(GL30.GL_FRAMEBUFFER, GL30.GL_COLOR_ATTACHMENT0, voxelTexture, 0, layer);
            if (layer == firstLayer) {
                checkFramebuffer("Voxel");
            }
            GL20.glUniform1i(layerLocation, layer);
            GL11.glDrawArrays(GL11.GL_TRIANGLES, 0, 3);
        }

        GL30.glBindVertexArray(0);
        GL20.glUseProgram(0);

        GL30.glBindFramebuffer(GL30.GL_DRAW_FRAMEBUFFER, previousDrawFbo);
        GL30.glBindFramebuffer(GL30.GL_READ_FRAMEBUFFER, previousReadFbo);
        GL11.glViewport(
                GENERATE_VIEWPORT.get(0), GENERATE_VIEWPORT.get(1), GENERATE_VIEWPORT.get(2), GENERATE_VIEWPORT.get(3));
        GL11.glEnable(GL11.GL_DEPTH_TEST);
        GL11.glEnable(GL11.GL_CULL_FACE);
    }

    /** Rebuilds the face buffer and the per-chunk draw commands from the voxel texture (see mesh.comp). */
    private static void buildMesh() {
        GL13.glActiveTexture(GL13.GL_TEXTURE0);
        GL11.glBindTexture(GL12.GL_TEXTURE_3D, voxelTexture);
        GL30.glBindBufferBase(GL43.GL_SHADER_STORAGE_BUFFER, 0, faceBuffer);
        GL30.glBindBufferBase(GL43.GL_SHADER_STORAGE_BUFFER, 1, chunkBuffer);
        GL30.glBindBufferBase(GL43.GL_SHADER_STORAGE_BUFFER, 2, drawBuffer);
        int groupsX = sizeX / 8;
        int groupsZ = sizeZ / 8;
        int groupsY = (allocatedLayers + 3) / 4;

        setMeshUniforms(meshCountProgram);
        GL43.glDispatchCompute(groupsX, groupsZ, groupsY);
        GL42.glMemoryBarrier(GL43.GL_SHADER_STORAGE_BARRIER_BIT);

        GL20.glUseProgram(meshScanProgram);
        GL30.glUniform1ui(GL20.glGetUniformLocation(meshScanProgram, "uChunkCount"), chunksX * chunksZ);
        GL30.glUniform1ui(GL20.glGetUniformLocation(meshScanProgram, "uCapacity"), MAX_FACES);
        GL43.glDispatchCompute(1, 1, 1);
        GL42.glMemoryBarrier(GL43.GL_SHADER_STORAGE_BARRIER_BIT);

        setMeshUniforms(meshEmitProgram);
        GL43.glDispatchCompute(groupsX, groupsZ, groupsY);
        // The faces are read by the vertex shader, the draw commands by the indirect draw.
        GL42.glMemoryBarrier(GL43.GL_SHADER_STORAGE_BARRIER_BIT | GL42.GL_COMMAND_BARRIER_BIT);
        checkFaceCount();

        for (int binding = 0; binding < 3; binding++) {
            GL30.glBindBufferBase(GL43.GL_SHADER_STORAGE_BUFFER, binding, 0);
        }
        GL11.glBindTexture(GL12.GL_TEXTURE_3D, 0);
        GL20.glUseProgram(0);
    }

    /**
     * Reads the total face count that mesh_scan.comp stored in chunk 0's pad field and warns when faces were dropped.
     * The readback waits for the mesher to finish, which is acceptable once per meshing.
     */
    private static void checkFaceCount() {
        GL42.glMemoryBarrier(GL42.GL_BUFFER_UPDATE_BARRIER_BIT);
        GL15.glBindBuffer(GL43.GL_SHADER_STORAGE_BUFFER, chunkBuffer);
        FACE_COUNT.clear();
        GL15.glGetBufferSubData(GL43.GL_SHADER_STORAGE_BUFFER, 12L, FACE_COUNT);
        GL15.glBindBuffer(GL43.GL_SHADER_STORAGE_BUFFER, 0);
        lastFaceCount = FACE_COUNT.get(0) & 0xffffffffL;

        long nowMs = Minecraft.getSystemTime();
        if (lastFaceCount > MAX_FACES) {
            if (!overflowing || nowMs - lastOverflowWarnMs >= 5000L) {
                CloudedHorizons.LOG.warn(
                        "Cloud mesh has {} faces, {} over the capacity of {}; the excess is not drawn",
                        lastFaceCount,
                        lastFaceCount - MAX_FACES,
                        MAX_FACES);
                lastOverflowWarnMs = nowMs;
            }
            overflowing = true;
        } else if (overflowing) {
            CloudedHorizons.LOG.info("Cloud mesh back within capacity: {} of {} faces", lastFaceCount, MAX_FACES);
            overflowing = false;
        }
    }

    /** Faces the last meshing produced, including any past the face buffer capacity. */
    public static long getFaceCount() {
        return lastFaceCount;
    }

    public static int getFaceCapacity() {
        return MAX_FACES;
    }

    private static void setMeshUniforms(int program) {
        GL20.glUseProgram(program);
        GL20.glUniform1i(GL20.glGetUniformLocation(program, "uVoxels"), 0);
        GL20.glUniform3i(GL20.glGetUniformLocation(program, "uDims"), sizeX, allocatedLayers, sizeZ);
        GL20.glUniform1i(GL20.glGetUniformLocation(program, "uChunkSize"), CHUNK_SIZE);
        GL20.glUniform1i(GL20.glGetUniformLocation(program, "uChunksX"), chunksX);
        GL30.glUniform1ui(GL20.glGetUniformLocation(program, "uCapacity"), MAX_FACES);
    }

    private static void checkFramebuffer(String name) {
        int status = GL30.glCheckFramebufferStatus(GL30.GL_FRAMEBUFFER);
        if (status != GL30.GL_FRAMEBUFFER_COMPLETE) {
            throw new IllegalStateException(name + " framebuffer incomplete: 0x" + Integer.toHexString(status));
        }
    }

    /** Compiles and links a compute program; {@code define}, if not null, is #defined before the source. */
    private static int createComputeProgram(String name, String define) {
        int shader = compileShader(GL43.GL_COMPUTE_SHADER, name, define);
        int program = GL20.glCreateProgram();
        GL20.glAttachShader(program, shader);
        GL20.glLinkProgram(program);
        GL20.glDeleteShader(shader);
        if (GL20.glGetProgrami(program, GL20.GL_LINK_STATUS) == GL11.GL_FALSE) {
            throw new IllegalStateException("Link failed (" + name + "): " + GL20.glGetProgramInfoLog(program, 8192));
        }
        return program;
    }

    /**
     * Links a program from one vertex shader and one or more fragment shader objects. Extra fragment shaders hold
     * shared functions (e.g. noise.fsh) that the main one declares as prototypes.
     */
    private static int createProgram(String vertexName, String... fragmentNames) {
        return createDefinedProgram(null, vertexName, fragmentNames);
    }

    private static int createDefinedProgram(String define, String vertexName, String... fragmentNames) {
        int program = GL20.glCreateProgram();
        int[] shaders = new int[fragmentNames.length + 1];
        shaders[0] = compileShader(GL20.GL_VERTEX_SHADER, vertexName, define);
        for (int i = 0; i < fragmentNames.length; i++) {
            shaders[i + 1] = compileShader(GL20.GL_FRAGMENT_SHADER, fragmentNames[i], define);
        }
        for (int shader : shaders) {
            GL20.glAttachShader(program, shader);
        }
        GL20.glLinkProgram(program);
        for (int shader : shaders) {
            GL20.glDeleteShader(shader);
        }
        if (GL20.glGetProgrami(program, GL20.GL_LINK_STATUS) == GL11.GL_FALSE) {
            throw new IllegalStateException(
                    "Link failed (" + vertexName + ", " + String.join(", ", fragmentNames) + "): "
                            + GL20.glGetProgramInfoLog(program, 8192));
        }
        return program;
    }

    private static int compileShader(int type, String name, String define) {
        String source = readShader(name);
        if (define != null) {
            // #define must follow the #version line.
            int eol = source.indexOf('\n') + 1;
            source = source.substring(0, eol) + "#define " + define + "\n" + source.substring(eol);
        }
        int shader = GL20.glCreateShader(type);
        GL20.glShaderSource(shader, source);
        GL20.glCompileShader(shader);
        if (GL20.glGetShaderi(shader, GL20.GL_COMPILE_STATUS) == GL11.GL_FALSE) {
            throw new IllegalStateException("Compile failed (" + name + "): " + GL20.glGetShaderInfoLog(shader, 8192));
        }
        return shader;
    }

    private static String readShader(String name) {
        String path = "/assets/cloudedhorizons/shaders/" + name;
        try (InputStream in = CloudRenderer.class.getResourceAsStream(path)) {
            if (in == null) {
                throw new IllegalStateException("Missing shader " + path);
            }
            return IOUtils.toString(in, StandardCharsets.UTF_8);
        } catch (IOException e) {
            throw new IllegalStateException("Could not read shader " + path, e);
        }
    }
}
