package com.cloudedhorizons.client;

import java.io.IOException;
import java.io.InputStream;
import java.nio.ByteBuffer;
import java.nio.FloatBuffer;
import java.nio.charset.StandardCharsets;

import net.minecraft.client.Minecraft;
import net.minecraft.client.renderer.GLAllocation;
import net.minecraft.client.renderer.OpenGlHelper;
import net.minecraft.client.renderer.entity.RenderManager;
import net.minecraft.util.Vec3;
import net.minecraft.world.World;

import org.lwjgl.opengl.GL11;
import org.lwjgl.opengl.GL12;
import org.lwjgl.opengl.GL13;
import org.lwjgl.opengl.GL15;
import org.lwjgl.opengl.GL20;
import org.lwjgl.opengl.GL30;
import org.lwjgl.opengl.GL32;

import org.apache.commons.io.IOUtils;

import com.cloudedhorizons.CloudedHorizons;
import com.cloudedhorizons.Config;

/**
 * Smoke-test GPU cloud renderer. A fragment shader generates the voxel volume into a 3D texture, one layer per draw.
 * A coarse occupancy grid ({@link #COARSE_X} x {@link #COARSE_Y} x {@link #COARSE_Z} voxels per cell) lets the
 * raymarch skip empty space. The field's time axis advances at {@link #getMorphSpeed()}. Regeneration is spread over
 * frames: each frame rebuilds one slab of {@link #COARSE_Y} layers plus its coarse layer, and a new pass starts every
 * {@link #REGEN_INTERVAL_TICKS} ticks at most while the clouds morph. Each frame, the volume's bounding box is drawn
 * and a DDA raymarch finds the voxel surface and writes its depth.
 */
public final class CloudRenderer {

    private static final int VOXEL_SIZE = 8;
    /** Requested horizontal size of the field in voxels (X and Z); limited by the GPU's 3D texture size. */
    private static final int FIELD_SIZE = 2560;
    /** Upper limit for the number of voxel layers, to keep the 3D texture and regeneration cost bounded. */
    private static final int MAX_LAYERS = 128;
    /** Coarse occupancy cell size in voxels; must match coarse.fsh and volume.fsh. */
    private static final int COARSE_X = 8;
    private static final int COARSE_Y = 4;
    private static final int COARSE_Z = 8;

    /** Actual horizontal size in voxels, set at initialisation. */
    private static int sizeX;
    private static int sizeZ;
    /** World position of the volume's minimum corner, centred on the world origin. */
    private static double originX;
    private static double originZ;
    private static final int SEED = 1;
    /** Regenerate the volume at most this often, in world ticks. */
    private static final double REGEN_INTERVAL_TICKS = 2.0D;

    private static double morphPhase;
    private static double lastWorldTime = Double.NaN;
    private static double lastRegenTime = Double.NEGATIVE_INFINITY;

    /** Minimum time between config writes, so sliders do not rewrite the file every frame. */
    private static final long SAVE_INTERVAL_MS = 1000L;
    private static boolean configDirty;
    private static long lastSaveMs;

    /** Set when a field parameter changes; a regeneration pass is started or queued on the next frame. */
    private static boolean fieldDirty;
    /** Slab being regenerated by the current pass, or -1 when no pass is running. */
    private static int regenSlab = -1;
    /** Another pass is needed after the current one, because the field changed while it ran. */
    private static boolean regenQueued;
    /** Number of voxel layers the 3D texture is currently allocated with. */
    private static int allocatedLayers;

    private static boolean initialized;
    private static boolean failed;

    private static int voxelTexture;
    private static int coarseTexture;
    private static int generateProgram;
    private static int coarseProgram;
    private static int volumeProgram;
    private static int emptyVao;
    private static int cubeVao;
    private static int cubeVbo;
    private static int generateFbo;

    private static final FloatBuffer MATRIX = GLAllocation.createDirectFloatBuffer(16);
    private static final FloatBuffer PROJECTION = GLAllocation.createDirectFloatBuffer(16);

    private CloudRenderer() {}

    public static double getMorphSpeed() {
        return Config.morphSpeed;
    }

    public static void setMorphSpeed(double speed) {
        Config.morphSpeed = speed;
        saveLater();
    }

    public static double getBaseY() {
        return Config.cloudHeight;
    }

    public static void setBaseY(double y) {
        // Only affects placement, so changing it needs no regeneration.
        Config.cloudHeight = y;
        saveLater();
    }

    /** Height of the cloud field in voxels. */
    public static int getFieldHeight() {
        return Config.fieldHeight;
    }

    public static void setFieldHeight(int voxels) {
        // The texture is reallocated and regenerated on the next frame (see render).
        Config.fieldHeight = voxels;
        saveLater();
    }

    public static double getNoiseScaleX() {
        return Config.noiseScaleX;
    }

    public static double getNoiseScaleY() {
        return Config.noiseScaleY;
    }

    public static double getNoiseScaleZ() {
        return Config.noiseScaleZ;
    }

    public static void setNoiseScaleX(double voxels) {
        Config.noiseScaleX = voxels;
        fieldChanged();
    }

    public static void setNoiseScaleY(double voxels) {
        Config.noiseScaleY = voxels;
        fieldChanged();
    }

    public static void setNoiseScaleZ(double voxels) {
        Config.noiseScaleZ = voxels;
        fieldChanged();
    }

    /** Marks the cloud settings for saving; {@link #saveIfDue()} writes them from the render loop. */
    private static void saveLater() {
        configDirty = true;
    }

    private static void saveIfDue() {
        long now = System.currentTimeMillis();
        if (configDirty && now - lastSaveMs >= SAVE_INTERVAL_MS) {
            configDirty = false;
            lastSaveMs = now;
            Config.saveClouds();
        }
    }

    private static void fieldChanged() {
        fieldDirty = true;
        saveLater();
    }

    /** Voxel layers to allocate: the configured field height, limited to 1..MAX_LAYERS. */
    private static int layers() {
        return Math.max(1, Math.min(MAX_LAYERS, Config.fieldHeight));
    }

    public static void render(Minecraft mc, World world, float partialTicks) {
        if (failed) {
            return;
        }
        if (!initialized) {
            try {
                initialize(mc);
            } catch (RuntimeException e) {
                failed = true;
                System.err.println("[Clouded Horizons] GPU cloud initialisation failed, clouds disabled: " + e);
                e.printStackTrace();
                return;
            }
        }
        if (layers() != allocatedLayers) {
            // New storage has undefined contents, so fill it completely before drawing.
            allocateTextures();
            generateAll(mc);
        }
        updateMorph(world, partialTicks);
        if (fieldDirty) {
            fieldDirty = false;
            startRegen();
        }
        if (regenSlab >= 0) {
            generateSlabs(mc, regenSlab, 1);
            regenSlab++;
            if (regenSlab >= slabs()) {
                regenSlab = regenQueued ? 0 : -1;
                regenQueued = false;
            }
        }
        saveIfDue();

        GL11.glGetFloatv(GL11.GL_MODELVIEW_MATRIX, MATRIX);
        GL11.glGetFloatv(GL11.GL_PROJECTION_MATRIX, PROJECTION);

        Vec3 colour = world.getCloudColour(partialTicks);
        double sunAngle = world.getCelestialAngle(partialTicks) * Math.PI * 2.0D;

        GL11.glEnable(GL11.GL_DEPTH_TEST);
        GL11.glDepthMask(true);
        GL11.glDisable(GL11.GL_BLEND);
        // Draw back faces so the box still rasterises when the camera is inside it.
        GL11.glEnable(GL11.GL_CULL_FACE);
        GL11.glCullFace(GL11.GL_FRONT);
        // The box can extend past the far plane; clamp instead of clipping it away.
        GL11.glEnable(GL32.GL_DEPTH_CLAMP);

        GL20.glUseProgram(volumeProgram);
        GL20.glUniformMatrix4fv(GL20.glGetUniformLocation(volumeProgram, "uProj"), false, PROJECTION);
        GL20.glUniformMatrix4fv(GL20.glGetUniformLocation(volumeProgram, "uView"), false, MATRIX);
        GL20.glUniform3f(
                GL20.glGetUniformLocation(volumeProgram, "uBoxMin"),
                (float) (originX - RenderManager.renderPosX),
                (float) (Config.cloudHeight - RenderManager.renderPosY),
                (float) (originZ - RenderManager.renderPosZ));
        GL20.glUniform3f(
                GL20.glGetUniformLocation(volumeProgram, "uBoxSize"),
                sizeX * VOXEL_SIZE,
                allocatedLayers * VOXEL_SIZE,
                sizeZ * VOXEL_SIZE);
        GL20.glUniform3f(GL20.glGetUniformLocation(volumeProgram, "uDims"), sizeX, allocatedLayers, sizeZ);
        GL20.glUniform1f(GL20.glGetUniformLocation(volumeProgram, "uVS"), VOXEL_SIZE);
        GL20.glUniform3f(
                GL20.glGetUniformLocation(volumeProgram, "uColour"),
                (float) colour.xCoord,
                (float) colour.yCoord,
                (float) colour.zCoord);
        GL20.glUniform3f(
                GL20.glGetUniformLocation(volumeProgram, "uSunDir"),
                (float) -Math.sin(sunAngle),
                (float) Math.cos(sunAngle),
                0.0F);
        GL20.glUniform1i(GL20.glGetUniformLocation(volumeProgram, "uVoxels"), 0);
        GL20.glUniform1i(GL20.glGetUniformLocation(volumeProgram, "uCoarse"), 1);

        GL13.glActiveTexture(GL13.GL_TEXTURE1);
        GL11.glBindTexture(GL12.GL_TEXTURE_3D, coarseTexture);
        GL13.glActiveTexture(GL13.GL_TEXTURE0);
        GL11.glBindTexture(GL12.GL_TEXTURE_3D, voxelTexture);
        GL30.glBindVertexArray(cubeVao);
        GL11.glDrawArrays(GL11.GL_TRIANGLES, 0, 36);
        GL30.glBindVertexArray(0);
        GL11.glBindTexture(GL12.GL_TEXTURE_3D, 0);
        GL13.glActiveTexture(GL13.GL_TEXTURE1);
        GL11.glBindTexture(GL12.GL_TEXTURE_3D, 0);
        GL13.glActiveTexture(GL13.GL_TEXTURE0);
        GL20.glUseProgram(0);

        GL11.glDisable(GL32.GL_DEPTH_CLAMP);
        GL11.glCullFace(GL11.GL_BACK);
        GL11.glColor4f(1.0F, 1.0F, 1.0F, 1.0F);
    }

    private static void initialize(Minecraft mc) {
        initialized = true;
        int max3d = GL11.glGetInteger(GL12.GL_MAX_3D_TEXTURE_SIZE);
        sizeX = Math.min(FIELD_SIZE, max3d);
        sizeZ = Math.min(FIELD_SIZE, max3d);
        if (sizeX < FIELD_SIZE) {
            CloudedHorizons.LOG.warn(
                    "GL_MAX_3D_TEXTURE_SIZE is {}; cloud field limited to {} voxels instead of {}",
                    max3d,
                    sizeX,
                    FIELD_SIZE);
        }
        originX = -sizeX * VOXEL_SIZE / 2.0D;
        originZ = -sizeZ * VOXEL_SIZE / 2.0D;

        generateProgram = createProgram("fullscreen.vsh", "generate.fsh", "noise.fsh");
        coarseProgram = createProgram("fullscreen.vsh", "coarse.fsh");
        volumeProgram = createProgram("volume.vsh", "volume.fsh");
        emptyVao = GL30.glGenVertexArrays();
        createCube();
        voxelTexture = createTexture3D();
        coarseTexture = createTexture3D();
        allocateTextures();
        generateFbo = GL30.glGenFramebuffers();
        generateAll(mc);
    }

    /** Starts a regeneration pass, or queues one if a pass is already running. */
    private static void startRegen() {
        if (regenSlab < 0) {
            regenSlab = 0;
        } else {
            regenQueued = true;
        }
    }

    /** Regenerates the whole volume at once and cancels any running pass. */
    private static void generateAll(Minecraft mc) {
        regenSlab = -1;
        regenQueued = false;
        fieldDirty = false;
        generateSlabs(mc, 0, slabs());
    }

    /** Number of slabs, each {@link #COARSE_Y} voxel layers (one coarse layer) thick. */
    private static int slabs() {
        return (allocatedLayers + COARSE_Y - 1) / COARSE_Y;
    }

    /**
     * Advances the morph phase by the game time elapsed since the last frame, so it stops while the game is paused
     * and a speed change does not make it jump.
     */
    private static void updateMorph(World world, float partialTicks) {
        double now = world.getTotalWorldTime() + partialTicks;
        if (Double.isNaN(lastWorldTime) || now < lastWorldTime || now - lastWorldTime > 100.0D) {
            // First frame, world change, or a large time skip: do not advance.
            lastWorldTime = now;
            return;
        }
        morphPhase += (now - lastWorldTime) / 20.0D * Config.morphSpeed;
        lastWorldTime = now;
        // Start the next pass once the previous one is done; passes take several frames.
        if (Config.morphSpeed != 0.0D && regenSlab < 0 && now - lastRegenTime >= REGEN_INTERVAL_TICKS) {
            lastRegenTime = now;
            startRegen();
        }
    }

    private static int createTexture3D() {
        int texture = GL11.glGenTextures();
        GL11.glBindTexture(GL12.GL_TEXTURE_3D, texture);
        GL11.glTexParameteri(GL12.GL_TEXTURE_3D, GL11.GL_TEXTURE_MIN_FILTER, GL11.GL_NEAREST);
        GL11.glTexParameteri(GL12.GL_TEXTURE_3D, GL11.GL_TEXTURE_MAG_FILTER, GL11.GL_NEAREST);
        GL11.glTexParameteri(GL12.GL_TEXTURE_3D, GL11.GL_TEXTURE_WRAP_S, GL12.GL_CLAMP_TO_EDGE);
        GL11.glTexParameteri(GL12.GL_TEXTURE_3D, GL11.GL_TEXTURE_WRAP_T, GL12.GL_CLAMP_TO_EDGE);
        GL11.glTexParameteri(GL12.GL_TEXTURE_3D, GL12.GL_TEXTURE_WRAP_R, GL12.GL_CLAMP_TO_EDGE);
        GL11.glTexParameteri(GL12.GL_TEXTURE_3D, GL12.GL_TEXTURE_MAX_LEVEL, 0);
        GL11.glBindTexture(GL12.GL_TEXTURE_3D, 0);
        return texture;
    }

    /** (Re)allocates the voxel and coarse texture storage for the configured field height. */
    private static void allocateTextures() {
        allocatedLayers = layers();
        // Layout (x, z, y): each generation draw fills one horizontal layer.
        allocateR8(voxelTexture, sizeX, sizeZ, allocatedLayers);
        allocateR8(coarseTexture, coarseX(), coarseZ(), slabs());
    }

    private static void allocateR8(int texture, int width, int height, int depth) {
        GL11.glBindTexture(GL12.GL_TEXTURE_3D, texture);
        GL12.glTexImage3D(
                GL12.GL_TEXTURE_3D,
                0,
                GL30.GL_R8,
                width,
                height,
                depth,
                0,
                GL11.GL_RED,
                GL11.GL_UNSIGNED_BYTE,
                (ByteBuffer) null);
        GL11.glBindTexture(GL12.GL_TEXTURE_3D, 0);
    }

    private static int coarseX() {
        return (sizeX + COARSE_X - 1) / COARSE_X;
    }

    private static int coarseZ() {
        return (sizeZ + COARSE_Z - 1) / COARSE_Z;
    }

    /**
     * Regenerates {@code count} slabs starting at {@code firstSlab}: runs the generation shader once per voxel layer,
     * then rebuilds the matching coarse layers, then restores Minecraft's GL state.
     */
    private static void generateSlabs(Minecraft mc, int firstSlab, int count) {
        int firstLayer = firstSlab * COARSE_Y;
        int endLayer = Math.min(allocatedLayers, (firstSlab + count) * COARSE_Y);
        int endSlab = Math.min(slabs(), firstSlab + count);

        // Nothing may sample the textures being written.
        GL13.glActiveTexture(GL13.GL_TEXTURE1);
        GL11.glBindTexture(GL12.GL_TEXTURE_3D, 0);
        GL13.glActiveTexture(GL13.GL_TEXTURE0);
        GL11.glBindTexture(GL12.GL_TEXTURE_3D, 0);
        GL30.glBindFramebuffer(GL30.GL_FRAMEBUFFER, generateFbo);
        GL11.glViewport(0, 0, sizeX, sizeZ);
        GL11.glDisable(GL11.GL_DEPTH_TEST);
        GL11.glDisable(GL11.GL_BLEND);
        GL11.glDisable(GL11.GL_CULL_FACE);

        GL20.glUseProgram(generateProgram);
        GL20.glUniform1f(GL20.glGetUniformLocation(generateProgram, "uVS"), VOXEL_SIZE);
        GL20.glUniform2f(
                GL20.glGetUniformLocation(generateProgram, "uOriginXZ"),
                (float) originX,
                (float) originZ);
        GL30.glUniform1ui(GL20.glGetUniformLocation(generateProgram, "uSeed"), SEED);
        GL20.glUniform3f(
                GL20.glGetUniformLocation(generateProgram, "uNoiseScale"),
                (float) Config.noiseScaleX,
                (float) Config.noiseScaleY,
                (float) Config.noiseScaleZ);
        // Wrapped so float precision in the shader stays good over long sessions; the jump is rare and slow.
        GL20.glUniform1f(GL20.glGetUniformLocation(generateProgram, "uEvolve"), (float) (morphPhase % 1000.0D));
        int layerLocation = GL20.glGetUniformLocation(generateProgram, "uLayer");

        GL30.glBindVertexArray(emptyVao);
        for (int layer = firstLayer; layer < endLayer; layer++) {
            GL30.glFramebufferTextureLayer(GL30.GL_FRAMEBUFFER, GL30.GL_COLOR_ATTACHMENT0, voxelTexture, 0, layer);
            if (layer == firstLayer) {
                checkFramebuffer("Voxel");
            }
            GL20.glUniform1i(layerLocation, layer);
            GL11.glDrawArrays(GL11.GL_TRIANGLES, 0, 3);
        }

        // Coarse occupancy for the slabs just written.
        GL20.glUseProgram(coarseProgram);
        GL20.glUniform1i(GL20.glGetUniformLocation(coarseProgram, "uVoxels"), 0);
        GL20.glUniform3i(GL20.glGetUniformLocation(coarseProgram, "uDims"), sizeX, allocatedLayers, sizeZ);
        int coarseLayerLocation = GL20.glGetUniformLocation(coarseProgram, "uLayer");
        GL11.glBindTexture(GL12.GL_TEXTURE_3D, voxelTexture);
        GL11.glViewport(0, 0, coarseX(), coarseZ());
        for (int slab = firstSlab; slab < endSlab; slab++) {
            GL30.glFramebufferTextureLayer(GL30.GL_FRAMEBUFFER, GL30.GL_COLOR_ATTACHMENT0, coarseTexture, 0, slab);
            if (slab == firstSlab) {
                checkFramebuffer("Coarse");
            }
            GL20.glUniform1i(coarseLayerLocation, slab);
            GL11.glDrawArrays(GL11.GL_TRIANGLES, 0, 3);
        }
        GL11.glBindTexture(GL12.GL_TEXTURE_3D, 0);

        GL30.glBindVertexArray(0);
        GL20.glUseProgram(0);

        GL30.glBindFramebuffer(GL30.GL_FRAMEBUFFER, 0);
        if (OpenGlHelper.isFramebufferEnabled()) {
            mc.getFramebuffer().bindFramebuffer(true);
        } else {
            GL11.glViewport(0, 0, mc.displayWidth, mc.displayHeight);
        }
        GL11.glEnable(GL11.GL_DEPTH_TEST);
        GL11.glEnable(GL11.GL_CULL_FACE);
    }

    private static void checkFramebuffer(String name) {
        int status = GL30.glCheckFramebufferStatus(GL30.GL_FRAMEBUFFER);
        if (status != GL30.GL_FRAMEBUFFER_COMPLETE) {
            throw new IllegalStateException(name + " framebuffer incomplete: 0x" + Integer.toHexString(status));
        }
    }

    /** Unit cube as 12 triangles, counter-clockwise when seen from outside. */
    private static void createCube() {
        float[][] quads = {
                { 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0 }, // +Y
                { 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1 }, // -Y
                { 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1 }, // +X
                { 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0 }, // -X
                { 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1 }, // +Z
                { 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0 }, // -Z
        };
        FloatBuffer data = GLAllocation.createDirectFloatBuffer(36 * 3);
        for (float[] q : quads) {
            for (int corner : new int[] { 0, 1, 2, 0, 2, 3 }) {
                data.put(q, corner * 3, 3);
            }
        }
        data.flip();

        cubeVao = GL30.glGenVertexArrays();
        GL30.glBindVertexArray(cubeVao);
        cubeVbo = GL15.glGenBuffers();
        GL15.glBindBuffer(GL15.GL_ARRAY_BUFFER, cubeVbo);
        GL15.glBufferData(GL15.GL_ARRAY_BUFFER, data, GL15.GL_STATIC_DRAW);
        GL20.glEnableVertexAttribArray(0);
        GL20.glVertexAttribPointer(0, 3, GL11.GL_FLOAT, false, 12, 0L);
        GL30.glBindVertexArray(0);
        GL15.glBindBuffer(GL15.GL_ARRAY_BUFFER, 0);
    }

    /**
     * Links a program from one vertex shader and one or more fragment shader objects. Extra fragment shaders hold
     * shared functions (e.g. noise.fsh) that the main one declares as prototypes.
     */
    private static int createProgram(String vertexName, String... fragmentNames) {
        int program = GL20.glCreateProgram();
        int[] shaders = new int[fragmentNames.length + 1];
        shaders[0] = compileShader(GL20.GL_VERTEX_SHADER, vertexName);
        for (int i = 0; i < fragmentNames.length; i++) {
            shaders[i + 1] = compileShader(GL20.GL_FRAGMENT_SHADER, fragmentNames[i]);
        }
        for (int shader : shaders) {
            GL20.glAttachShader(program, shader);
        }
        GL20.glLinkProgram(program);
        for (int shader : shaders) {
            GL20.glDeleteShader(shader);
        }
        if (GL20.glGetProgrami(program, GL20.GL_LINK_STATUS) == GL11.GL_FALSE) {
            throw new IllegalStateException(
                    "Link failed (" + vertexName + ", " + String.join(", ", fragmentNames) + "): "
                            + GL20.glGetProgramInfoLog(program, 8192));
        }
        return program;
    }

    private static int compileShader(int type, String name) {
        int shader = GL20.glCreateShader(type);
        GL20.glShaderSource(shader, readShader(name));
        GL20.glCompileShader(shader);
        if (GL20.glGetShaderi(shader, GL20.GL_COMPILE_STATUS) == GL11.GL_FALSE) {
            throw new IllegalStateException("Compile failed (" + name + "): " + GL20.glGetShaderInfoLog(shader, 8192));
        }
        return shader;
    }

    private static String readShader(String name) {
        String path = "/assets/cloudedhorizons/shaders/" + name;
        try (InputStream in = CloudRenderer.class.getResourceAsStream(path)) {
            if (in == null) {
                throw new IllegalStateException("Missing shader " + path);
            }
            return IOUtils.toString(in, StandardCharsets.UTF_8);
        } catch (IOException e) {
            throw new IllegalStateException("Could not read shader " + path, e);
        }
    }
}
